// flow-typed signature: 2e1fc0637905c5081a098ef644452e52
// flow-typed version: <<STUB>>/animated_v^0.2.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animated'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animated' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animated/lib/__tests__/Animated-test' {
  declare module.exports: any;
}

declare module 'animated/lib/__tests__/Easing-test' {
  declare module.exports: any;
}

declare module 'animated/lib/__tests__/Interpolation-test' {
  declare module.exports: any;
}

declare module 'animated/lib/Animated' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedAddition' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedInterpolation' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedModulo' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedMultiplication' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedProps' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedTemplate' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedTracking' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedTransform' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedValue' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedValueXY' {
  declare module.exports: any;
}

declare module 'animated/lib/AnimatedWithChildren' {
  declare module.exports: any;
}

declare module 'animated/lib/Animation' {
  declare module.exports: any;
}

declare module 'animated/lib/bezier' {
  declare module.exports: any;
}

declare module 'animated/lib/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'animated/lib/DecayAnimation' {
  declare module.exports: any;
}

declare module 'animated/lib/Easing' {
  declare module.exports: any;
}

declare module 'animated/lib/guid' {
  declare module.exports: any;
}

declare module 'animated/lib/index' {
  declare module.exports: any;
}

declare module 'animated/lib/injectable/ApplyAnimatedValues' {
  declare module.exports: any;
}

declare module 'animated/lib/injectable/CancelAnimationFrame' {
  declare module.exports: any;
}

declare module 'animated/lib/injectable/FlattenStyle' {
  declare module.exports: any;
}

declare module 'animated/lib/injectable/InteractionManager' {
  declare module.exports: any;
}

declare module 'animated/lib/injectable/RequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'animated/lib/Interpolation' {
  declare module.exports: any;
}

declare module 'animated/lib/isAnimated' {
  declare module.exports: any;
}

declare module 'animated/lib/SetPolyfill' {
  declare module.exports: any;
}

declare module 'animated/lib/SpringAnimation' {
  declare module.exports: any;
}

declare module 'animated/lib/SpringConfig' {
  declare module.exports: any;
}

declare module 'animated/lib/targets/react-dom' {
  declare module.exports: any;
}

declare module 'animated/lib/targets/react-native' {
  declare module.exports: any;
}

declare module 'animated/lib/TimingAnimation' {
  declare module.exports: any;
}

declare module 'animated/src/__tests__/Animated-test' {
  declare module.exports: any;
}

declare module 'animated/src/__tests__/Easing-test' {
  declare module.exports: any;
}

declare module 'animated/src/__tests__/Interpolation-test' {
  declare module.exports: any;
}

declare module 'animated/src/Animated' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedAddition' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedInterpolation' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedModulo' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedMultiplication' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedProps' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedTemplate' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedTracking' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedTransform' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedValue' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedValueXY' {
  declare module.exports: any;
}

declare module 'animated/src/AnimatedWithChildren' {
  declare module.exports: any;
}

declare module 'animated/src/Animation' {
  declare module.exports: any;
}

declare module 'animated/src/bezier' {
  declare module.exports: any;
}

declare module 'animated/src/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'animated/src/DecayAnimation' {
  declare module.exports: any;
}

declare module 'animated/src/Easing' {
  declare module.exports: any;
}

declare module 'animated/src/guid' {
  declare module.exports: any;
}

declare module 'animated/src/index' {
  declare module.exports: any;
}

declare module 'animated/src/injectable/ApplyAnimatedValues' {
  declare module.exports: any;
}

declare module 'animated/src/injectable/CancelAnimationFrame' {
  declare module.exports: any;
}

declare module 'animated/src/injectable/FlattenStyle' {
  declare module.exports: any;
}

declare module 'animated/src/injectable/InteractionManager' {
  declare module.exports: any;
}

declare module 'animated/src/injectable/RequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'animated/src/Interpolation' {
  declare module.exports: any;
}

declare module 'animated/src/isAnimated' {
  declare module.exports: any;
}

declare module 'animated/src/SetPolyfill' {
  declare module.exports: any;
}

declare module 'animated/src/SpringAnimation' {
  declare module.exports: any;
}

declare module 'animated/src/SpringConfig' {
  declare module.exports: any;
}

declare module 'animated/src/targets/react-dom' {
  declare module.exports: any;
}

declare module 'animated/src/targets/react-native' {
  declare module.exports: any;
}

declare module 'animated/src/TimingAnimation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animated/lib/__tests__/Animated-test.js' {
  declare module.exports: $Exports<'animated/lib/__tests__/Animated-test'>;
}
declare module 'animated/lib/__tests__/Easing-test.js' {
  declare module.exports: $Exports<'animated/lib/__tests__/Easing-test'>;
}
declare module 'animated/lib/__tests__/Interpolation-test.js' {
  declare module.exports: $Exports<'animated/lib/__tests__/Interpolation-test'>;
}
declare module 'animated/lib/Animated.js' {
  declare module.exports: $Exports<'animated/lib/Animated'>;
}
declare module 'animated/lib/AnimatedAddition.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedAddition'>;
}
declare module 'animated/lib/AnimatedInterpolation.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedInterpolation'>;
}
declare module 'animated/lib/AnimatedModulo.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedModulo'>;
}
declare module 'animated/lib/AnimatedMultiplication.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedMultiplication'>;
}
declare module 'animated/lib/AnimatedProps.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedProps'>;
}
declare module 'animated/lib/AnimatedStyle.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedStyle'>;
}
declare module 'animated/lib/AnimatedTemplate.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedTemplate'>;
}
declare module 'animated/lib/AnimatedTracking.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedTracking'>;
}
declare module 'animated/lib/AnimatedTransform.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedTransform'>;
}
declare module 'animated/lib/AnimatedValue.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedValue'>;
}
declare module 'animated/lib/AnimatedValueXY.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedValueXY'>;
}
declare module 'animated/lib/AnimatedWithChildren.js' {
  declare module.exports: $Exports<'animated/lib/AnimatedWithChildren'>;
}
declare module 'animated/lib/Animation.js' {
  declare module.exports: $Exports<'animated/lib/Animation'>;
}
declare module 'animated/lib/bezier.js' {
  declare module.exports: $Exports<'animated/lib/bezier'>;
}
declare module 'animated/lib/createAnimatedComponent.js' {
  declare module.exports: $Exports<'animated/lib/createAnimatedComponent'>;
}
declare module 'animated/lib/DecayAnimation.js' {
  declare module.exports: $Exports<'animated/lib/DecayAnimation'>;
}
declare module 'animated/lib/Easing.js' {
  declare module.exports: $Exports<'animated/lib/Easing'>;
}
declare module 'animated/lib/guid.js' {
  declare module.exports: $Exports<'animated/lib/guid'>;
}
declare module 'animated/lib/index.js' {
  declare module.exports: $Exports<'animated/lib/index'>;
}
declare module 'animated/lib/injectable/ApplyAnimatedValues.js' {
  declare module.exports: $Exports<'animated/lib/injectable/ApplyAnimatedValues'>;
}
declare module 'animated/lib/injectable/CancelAnimationFrame.js' {
  declare module.exports: $Exports<'animated/lib/injectable/CancelAnimationFrame'>;
}
declare module 'animated/lib/injectable/FlattenStyle.js' {
  declare module.exports: $Exports<'animated/lib/injectable/FlattenStyle'>;
}
declare module 'animated/lib/injectable/InteractionManager.js' {
  declare module.exports: $Exports<'animated/lib/injectable/InteractionManager'>;
}
declare module 'animated/lib/injectable/RequestAnimationFrame.js' {
  declare module.exports: $Exports<'animated/lib/injectable/RequestAnimationFrame'>;
}
declare module 'animated/lib/Interpolation.js' {
  declare module.exports: $Exports<'animated/lib/Interpolation'>;
}
declare module 'animated/lib/isAnimated.js' {
  declare module.exports: $Exports<'animated/lib/isAnimated'>;
}
declare module 'animated/lib/SetPolyfill.js' {
  declare module.exports: $Exports<'animated/lib/SetPolyfill'>;
}
declare module 'animated/lib/SpringAnimation.js' {
  declare module.exports: $Exports<'animated/lib/SpringAnimation'>;
}
declare module 'animated/lib/SpringConfig.js' {
  declare module.exports: $Exports<'animated/lib/SpringConfig'>;
}
declare module 'animated/lib/targets/react-dom.js' {
  declare module.exports: $Exports<'animated/lib/targets/react-dom'>;
}
declare module 'animated/lib/targets/react-native.js' {
  declare module.exports: $Exports<'animated/lib/targets/react-native'>;
}
declare module 'animated/lib/TimingAnimation.js' {
  declare module.exports: $Exports<'animated/lib/TimingAnimation'>;
}
declare module 'animated/src/__tests__/Animated-test.js' {
  declare module.exports: $Exports<'animated/src/__tests__/Animated-test'>;
}
declare module 'animated/src/__tests__/Easing-test.js' {
  declare module.exports: $Exports<'animated/src/__tests__/Easing-test'>;
}
declare module 'animated/src/__tests__/Interpolation-test.js' {
  declare module.exports: $Exports<'animated/src/__tests__/Interpolation-test'>;
}
declare module 'animated/src/Animated.js' {
  declare module.exports: $Exports<'animated/src/Animated'>;
}
declare module 'animated/src/AnimatedAddition.js' {
  declare module.exports: $Exports<'animated/src/AnimatedAddition'>;
}
declare module 'animated/src/AnimatedInterpolation.js' {
  declare module.exports: $Exports<'animated/src/AnimatedInterpolation'>;
}
declare module 'animated/src/AnimatedModulo.js' {
  declare module.exports: $Exports<'animated/src/AnimatedModulo'>;
}
declare module 'animated/src/AnimatedMultiplication.js' {
  declare module.exports: $Exports<'animated/src/AnimatedMultiplication'>;
}
declare module 'animated/src/AnimatedProps.js' {
  declare module.exports: $Exports<'animated/src/AnimatedProps'>;
}
declare module 'animated/src/AnimatedStyle.js' {
  declare module.exports: $Exports<'animated/src/AnimatedStyle'>;
}
declare module 'animated/src/AnimatedTemplate.js' {
  declare module.exports: $Exports<'animated/src/AnimatedTemplate'>;
}
declare module 'animated/src/AnimatedTracking.js' {
  declare module.exports: $Exports<'animated/src/AnimatedTracking'>;
}
declare module 'animated/src/AnimatedTransform.js' {
  declare module.exports: $Exports<'animated/src/AnimatedTransform'>;
}
declare module 'animated/src/AnimatedValue.js' {
  declare module.exports: $Exports<'animated/src/AnimatedValue'>;
}
declare module 'animated/src/AnimatedValueXY.js' {
  declare module.exports: $Exports<'animated/src/AnimatedValueXY'>;
}
declare module 'animated/src/AnimatedWithChildren.js' {
  declare module.exports: $Exports<'animated/src/AnimatedWithChildren'>;
}
declare module 'animated/src/Animation.js' {
  declare module.exports: $Exports<'animated/src/Animation'>;
}
declare module 'animated/src/bezier.js' {
  declare module.exports: $Exports<'animated/src/bezier'>;
}
declare module 'animated/src/createAnimatedComponent.js' {
  declare module.exports: $Exports<'animated/src/createAnimatedComponent'>;
}
declare module 'animated/src/DecayAnimation.js' {
  declare module.exports: $Exports<'animated/src/DecayAnimation'>;
}
declare module 'animated/src/Easing.js' {
  declare module.exports: $Exports<'animated/src/Easing'>;
}
declare module 'animated/src/guid.js' {
  declare module.exports: $Exports<'animated/src/guid'>;
}
declare module 'animated/src/index.js' {
  declare module.exports: $Exports<'animated/src/index'>;
}
declare module 'animated/src/injectable/ApplyAnimatedValues.js' {
  declare module.exports: $Exports<'animated/src/injectable/ApplyAnimatedValues'>;
}
declare module 'animated/src/injectable/CancelAnimationFrame.js' {
  declare module.exports: $Exports<'animated/src/injectable/CancelAnimationFrame'>;
}
declare module 'animated/src/injectable/FlattenStyle.js' {
  declare module.exports: $Exports<'animated/src/injectable/FlattenStyle'>;
}
declare module 'animated/src/injectable/InteractionManager.js' {
  declare module.exports: $Exports<'animated/src/injectable/InteractionManager'>;
}
declare module 'animated/src/injectable/RequestAnimationFrame.js' {
  declare module.exports: $Exports<'animated/src/injectable/RequestAnimationFrame'>;
}
declare module 'animated/src/Interpolation.js' {
  declare module.exports: $Exports<'animated/src/Interpolation'>;
}
declare module 'animated/src/isAnimated.js' {
  declare module.exports: $Exports<'animated/src/isAnimated'>;
}
declare module 'animated/src/SetPolyfill.js' {
  declare module.exports: $Exports<'animated/src/SetPolyfill'>;
}
declare module 'animated/src/SpringAnimation.js' {
  declare module.exports: $Exports<'animated/src/SpringAnimation'>;
}
declare module 'animated/src/SpringConfig.js' {
  declare module.exports: $Exports<'animated/src/SpringConfig'>;
}
declare module 'animated/src/targets/react-dom.js' {
  declare module.exports: $Exports<'animated/src/targets/react-dom'>;
}
declare module 'animated/src/targets/react-native.js' {
  declare module.exports: $Exports<'animated/src/targets/react-native'>;
}
declare module 'animated/src/TimingAnimation.js' {
  declare module.exports: $Exports<'animated/src/TimingAnimation'>;
}
